package tn.esprit.spring.controllers;

import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor; // Keep this
import org.springframework.beans.factory.annotation.Autowired; // Can remove these @Autowired if using final fields with @RequiredArgsConstructor
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.*;
import tn.esprit.spring.entities.AuthResponse;
import tn.esprit.spring.entities.LoginRequest;
import tn.esprit.spring.entities.User;
import tn.esprit.spring.entities.UserDTO;
import tn.esprit.spring.repositories.UserRepository;
import tn.esprit.spring.services.UserService;
import tn.esprit.spring.services.implementations.EmailService;
import tn.esprit.spring.services.implementations.PasswordResetService;

import java.util.*;


@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor // This generates a constructor for all 'final' fields
public class AuthController {

    private final UserService userService;
    private final UserRepository userRepository;
    // Make these fields 'final' so @RequiredArgsConstructor includes them in the constructor
    private final PasswordResetService passwordResetService; // No need for @Autowired here with @RequiredArgsConstructor
    private final EmailService emailService;                 // No need for @Autowired here with @RequiredArgsConstructor

    // The constructor will now be implicitly generated by Lombok like this:
    /*
    public AuthController(UserService userService, UserRepository userRepository,
                          PasswordResetService passwordResetService, EmailService emailService) {
        this.userService = userService;
        this.userRepository = userRepository;
        this.passwordResetService = passwordResetService;
        this.emailService = emailService;
    }
    */

    private String generateTempPassword() {
        // Your existing logic
        int length = 12;
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        Random random = new Random();
        StringBuilder password = new StringBuilder(length);

        for (int i = 0; i < length; i++) {
            password.append(chars.charAt(random.nextInt(chars.length())));
        }
        return password.toString();
    }


    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@RequestBody UserDTO userDTO) {
        System.out.println("Received user: " + userDTO);
        AuthResponse response = userService.register(userDTO);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@RequestBody LoginRequest request) {
        AuthResponse response = userService.login(request);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/forgot-password")
    public ResponseEntity<?> forgotPassword(@RequestBody Map<String, String> request) {
        String email = request.get("email");

        if (email == null || email.isEmpty()) {
            return ResponseEntity.badRequest().body("Email is required.");
        }

        Optional<User> userOpt = userRepository.findByEmail(email);
        if (userOpt.isEmpty()) {
            // It's often good practice not to reveal whether an email exists for security reasons
            // But based on your original code's behavior, returning NOT_FOUND
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Email introuvable");
        }

        User user = userOpt.get();

        try {
            // This is the line where the NPE occurred
            // Now emailService should be properly injected
            String tempPassword = emailService.sendTemporaryPassword(email);

            BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
            user.setPassword(encoder.encode(tempPassword));
            userRepository.save(user);

            Map<String, String> response = new HashMap<>();
            response.put("tempPassword", tempPassword);

            return ResponseEntity.ok(response);

        } catch (Exception e) {
            System.err.println("Error sending temporary password: " + e.getMessage());
            // It's good to provide a more generic error message to the client for security
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Une erreur est survenue lors de l'envoi du mot de passe temporaire.");
        }
    }


    @PostMapping("/reset-password")
    public ResponseEntity<?> resetPassword(@RequestBody Map<String, String> request) {
        String email = request.get("email");
        String tempPassword = request.get("tempPassword");
        String newPassword = request.get("newPassword");

        Optional<User> userOpt = userRepository.findByEmail(email);
        if (userOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(Map.of("message", "Email introuvable"));
        }

        User user = userOpt.get();
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();

        if (!encoder.matches(tempPassword, user.getPassword())) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("message", "Mot de passe temporaire invalide"));
        }

        user.setPassword(encoder.encode(newPassword));
        userRepository.save(user);

        return ResponseEntity
                .ok()
                .contentType(MediaType.APPLICATION_JSON)
                .body(Map.of("message", "Mot de passe mis à jour avec succès"));

    }
}