package tn.esprit.spring.controllers;

import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor; // Keep this
import org.springframework.beans.factory.annotation.Autowired; // Can remove these @Autowired if using final fields with @RequiredArgsConstructor
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.*;
import tn.esprit.spring.entities.AuthResponse;
import tn.esprit.spring.entities.LoginRequest;
import tn.esprit.spring.entities.User;
import tn.esprit.spring.entities.UserDTO;
import tn.esprit.spring.repositories.UserRepository;
import tn.esprit.spring.services.UserService;
import tn.esprit.spring.services.implementations.EmailService;
import tn.esprit.spring.services.implementations.PasswordResetService;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.*;


@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor // This generates a constructor for all 'final' fields
public class AuthController {

    private final UserService userService;
    private final UserRepository userRepository;
    // Make these fields 'final' so @RequiredArgsConstructor includes them in the constructor
    private final PasswordResetService passwordResetService; // No need for @Autowired here with @RequiredArgsConstructor
    private final EmailService emailService;                 // No need for @Autowired here with @RequiredArgsConstructor

    // The constructor will now be implicitly generated by Lombok like this:
    /*
    public AuthController(UserService userService, UserRepository userRepository,
                          PasswordResetService passwordResetService, EmailService emailService) {
        this.userService = userService;
        this.userRepository = userRepository;
        this.passwordResetService = passwordResetService;
        this.emailService = emailService;
    }
    */

    private String generateTempPassword() {
        // Your existing logic
        int length = 12;
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        Random random = new Random();
        StringBuilder password = new StringBuilder(length);

        for (int i = 0; i < length; i++) {
            password.append(chars.charAt(random.nextInt(chars.length())));
        }
        return password.toString();
    }


    // Step 1: Register user with email confirmation
    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@RequestBody UserDTO userDTO) {
        // Step 2: Register user (save in database, not activated yet)
        AuthResponse authResponse = userService.register(userDTO);
        
        // Get the actual user from database to set confirmation fields
        Optional<User> userOpt = userRepository.findByEmail(userDTO.email);
        if (userOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new AuthResponse("Error creating user"));
        }
        
        User user = userOpt.get();
        
        // Step 3: Generate confirmation code and expiration time
        String confirmationCode = generateTempPassword().substring(0, 6); // 6-digit code
        
        // Calculate expiration time in milliseconds (10 minutes from now)
        long expirationTimeMillis = System.currentTimeMillis() + 10 * 60 * 1000; // 10 minutes expiration
        
        // Step 4: Save confirmation code and expiration in the database
        user.setConfirmationCode(confirmationCode);
        user.setConfirmationCodeExpiration(LocalDateTime.ofInstant(
            java.time.Instant.ofEpochMilli(expirationTimeMillis), 
            ZoneId.systemDefault()
        )); // Use LocalDateTime as per entity
        user.setActive(false); // Ensure user is not active until confirmed
        userRepository.save(user);
        
        // Step 5: Send confirmation email with the code
        try {
            emailService.sendEmail(user.getEmail(), "Please confirm your registration",
                    "Your confirmation code is: " + confirmationCode);
            return ResponseEntity.ok(new AuthResponse("Please check your email for the confirmation code."));
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new AuthResponse("Error sending confirmation email"));
        }
    }

    // Step 6: Confirm email using the confirmation code
    @PostMapping("/confirm-email")
    public ResponseEntity<?> confirmEmail(@RequestBody Map<String, String> request) {
        String email = request.get("email");
        String code = request.get("code");
        
        // Step 7: Validate the confirmation code
        Optional<User> userOpt = userRepository.findByEmail(email);
        if (userOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Email not found");
        }
        
        User user = userOpt.get();
        
        // Check if confirmation code exists
        if (user.getConfirmationCode() == null) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("No confirmation code found");
        }
        
        // Check if the code matches
        if (!user.getConfirmationCode().equals(code)) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Invalid confirmation code");
        }
        
        // Check if code is expired (confirmationCodeExpiration is Long in milliseconds)
        long currentTimeMillis = System.currentTimeMillis();
        if (user.getConfirmationCodeExpiration() != null && currentTimeMillis > user.getConfirmationCodeExpiration().atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Confirmation code expired");
        }
        
        // Step 8: Activate user
        user.setActive(true);
        user.setConfirmationCode(null); // Clear the confirmation code
        user.setConfirmationCodeExpiration(null); // Clear expiration time
        userRepository.save(user);
        
        return ResponseEntity.ok("Email confirmed successfully");
    }

   /* @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@RequestBody UserDTO userDTO) {
        System.out.println("Received user: " + userDTO);
        AuthResponse response = userService.register(userDTO);
        return ResponseEntity.ok(response);
    }*/

    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@RequestBody LoginRequest request) {
        AuthResponse response = userService.login(request);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/forgot-password")
    public ResponseEntity<?> forgotPassword(@RequestBody Map<String, String> request) {
        String email = request.get("email");

        if (email == null || email.isEmpty()) {
            return ResponseEntity.badRequest().body("Email is required.");
        }

        Optional<User> userOpt = userRepository.findByEmail(email);
        if (userOpt.isEmpty()) {
            // It's often good practice not to reveal whether an email exists for security reasons
            // But based on your original code's behavior, returning NOT_FOUND
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Email introuvable");
        }

        User user = userOpt.get();

        try {
            // This is the line where the NPE occurred
            // Now emailService should be properly injected
            String tempPassword = emailService.sendTemporaryPassword(email);

            BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
            user.setPassword(encoder.encode(tempPassword));
            userRepository.save(user);

            Map<String, String> response = new HashMap<>();
            response.put("tempPassword", tempPassword);

            return ResponseEntity.ok(response);

        } catch (Exception e) {
            System.err.println("Error sending temporary password: " + e.getMessage());
            // It's good to provide a more generic error message to the client for security
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Une erreur est survenue lors de l'envoi du mot de passe temporaire.");
        }
    }


    @PostMapping("/reset-password")
    public ResponseEntity<?> resetPassword(@RequestBody Map<String, String> request) {
        String email = request.get("email");
        String tempPassword = request.get("tempPassword");
        String newPassword = request.get("newPassword");

        Optional<User> userOpt = userRepository.findByEmail(email);
        if (userOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(Map.of("message", "Email introuvable"));
        }

        User user = userOpt.get();
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();

        if (!encoder.matches(tempPassword, user.getPassword())) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("message", "Mot de passe temporaire invalide"));
        }

        user.setPassword(encoder.encode(newPassword));
        userRepository.save(user);

        return ResponseEntity
                .ok()
                .contentType(MediaType.APPLICATION_JSON)
                .body(Map.of("message", "Mot de passe mis à jour avec succès"));

    }
}
