# Identifiants SonarCloud (obtenus lors de la cr?ation du projet)
sonar.projectKey=backendspring
sonar.organization=amina333
sonar.host.url=https://sonarcloud.io
sonar.login=699bfad94e6556fad3f5f28612b137ff728340cf
# Code source Java
sonar.sources=src
sonar.language=java
sonar.java.binaries=target

# Pour ?viter d?analyser les fichiers inutiles
sonar.exclusions=**/test/**, **/target/**, **/*.md, **/*.yml, **/*.yaml

# Affichage console plus propre
sonar.verbose=false