# Identifiants SonarCloud de l'organisation commune
sonar.projectKey=PIDEVSpringProject_BackendSpring
sonar.organization=pidevspringproject
sonar.host.url=https://sonarcloud.io

# Code source Java
sonar.sources=src
sonar.language=java
sonar.java.binaries=target

# Pour éviter d?analyser les fichiers inutiles
sonar.exclusions=**/test/**, **/target/**, **/*.md, **/*.yml, **/*.yaml

# Affichage console plus propre
sonar.verbose=false
