# Identifiants SonarCloud (obtenus lors de la cr?ation du projet)
sonar.projectKey=rafik12342_backend
sonar.organization=Rafik12342
sonar.host.url=https://sonarcloud.io
sonar.login=efc7ca5d7c9122f6b3a47c060685dad0afbc239d
# Code source Java
sonar.sources=src
sonar.language=java
sonar.java.binaries=target

# Pour ?viter d?analyser les fichiers inutiles
sonar.exclusions=**/test/**, **/target/**, **/*.md, **/*.yml, **/*.yaml

# Affichage console plus propre
sonar.verbose=false