package tn.esprit.spring.entities;

import lombok.AllArgsConstructor;
import lombok.Data;

import java.time.LocalDateTime;

@Data
public class AuthResponse {
    private String token;
    private String confirmationCode;  // Existing field for the confirmation code
    private LocalDateTime confirmationCodeExpiration;  // New field for expiration time

    // Constructor with only token
    public AuthResponse(String token) {
        this.token = token;
    }

    // Constructor with token, confirmation code, and expiration time
    public AuthResponse(String token, String confirmationCode, LocalDateTime confirmationCodeExpiration) {
        this.token = token;
        this.confirmationCode = confirmationCode;
        this.confirmationCodeExpiration = confirmationCodeExpiration;
    }

    // Getter and Setter for confirmationCodeExpiration (Automatically generated by Lombok's @Data)
}
